export enum KEYS {
  Backspace = "Backspace",
  Tab = "Tab",
  Enter = "Enter",
  Shift = "shift",
  Ctrl = "ctrl",
  Alt = "alt",
  Meta = "meta",
  Escape = "Escape",
  Space = "Space",
  pageUp = "PageUp",
  pageDown = "PageDown",
  end = "End",
  home = "Home",
  left = "ArrowLeft",
  up = "ArrowUp",
  right = "ArrowRight",
  down = "ArrowDown",
  printScreen = "PrintScreen",
  insert = "Insert",
  delete = "Delete",
  zero = "0",
  one = "1",
  two = "2",
  three = "3",
  four = "4",
  five = "5",
  six = "6",
  seven = "7",
  eight = "8",
  nine = "9",
  a = "a",
  b = "b",
  c = "c",
  d = "d",
  e = "e",
  f = "f",
  g = "g",
  h = "h",
  i = "i",
  j = "j",
  k = "k",
  l = "l",
  m = "m",
  n = "n",
  o = "o",
  p = "p",
  q = "q",
  r = "r",
  s = "s",
  t = "t",
  u = "u",
  v = "v",
  w = "w",
  x = "x",
  y = "y",
  z = "z",
  numpad0 = "0",
  numpad1 = "1",
  numpad2 = "2",
  numpad3 = "3",
  numpad4 = "4",
  numpad5 = "5",
  numpad6 = "6",
  numpad7 = "7",
  numpad8 = "8",
  numpad9 = "9",
  multiply = "*",
  add = "+",
  subtract = "-",
  decimal = ".",
  divide = "/",
  f1 = "F1",
  f2 = "F2",
  f3 = "F3",
  f4 = "F4",
  f5 = "F5",
  f6 = "F6",
  f7 = "F7",
  f8 = "F8",
  f9 = "F9",
  f10 = "F10",
  f11 = "F11",
  f12 = "F12",
  numLock = "NumLock",
  scrollLock = "ScrollLock",
  semicolon = ";",
  equals = "=",
  comma = ",",
  dash = "-",
  period = ".",
  forwardSlash = "/",
  graveAccent = "`",
  openBracket = "[",
  backSlash = "\\",
  closeBracket = "]",
  singleQuote = "'",
  questionMark = "?"
}

export const KEY_LABELS: Record<KEYS, string> = {
  [KEYS.Backspace]: "\u232b",
  [KEYS.delete]: "\u2326",
  [KEYS.Meta]: "\u2318",
  [KEYS.Alt]: "\u2325",
  [KEYS.Ctrl]: "\u2303",
  [KEYS.Shift]: "\u21E7",
  [KEYS.Enter]: "\u23CE",
  [KEYS.Escape]: "\u238B",
  [KEYS.Tab]: "\u21E5",
  [KEYS.pageUp]: "\u21DE",
  [KEYS.pageDown]: "\u21DF",
  [KEYS.home]: "\u2196",
  [KEYS.end]: "\u2198",
  [KEYS.left]: "\u2190",
  [KEYS.up]: "\u2191",
  [KEYS.right]: "\u2192",
  [KEYS.down]: "\u2193",
  [KEYS.Space]: "\u2423",
  [KEYS.printScreen]: "",
  [KEYS.insert]: "",
  [KEYS.zero]: "0",
  [KEYS.one]: "1",
  [KEYS.two]: "2",
  [KEYS.three]: "3",
  [KEYS.four]: "4",
  [KEYS.five]: "5",
  [KEYS.six]: "6",
  [KEYS.seven]: "7",
  [KEYS.eight]: "8",
  [KEYS.nine]: "9",
  [KEYS.a]: "A",
  [KEYS.b]: "B",
  [KEYS.c]: "C",
  [KEYS.d]: "D",
  [KEYS.e]: "E",
  [KEYS.f]: "F",
  [KEYS.g]: "G",
  [KEYS.h]: "H",
  [KEYS.i]: "I",
  [KEYS.j]: "J",
  [KEYS.k]: "K",
  [KEYS.l]: "L",
  [KEYS.m]: "M",
  [KEYS.n]: "N",
  [KEYS.o]: "O",
  [KEYS.p]: "P",
  [KEYS.q]: "Q",
  [KEYS.r]: "R",
  [KEYS.s]: "S",
  [KEYS.t]: "T",
  [KEYS.u]: "U",
  [KEYS.v]: "V",
  [KEYS.w]: "W",
  [KEYS.x]: "X",
  [KEYS.y]: "Y",
  [KEYS.z]: "Z",
  "*": "*",
  "+": "+",
  "-": "-",
  ".": ".",
  "/": "/",
  [KEYS.f1]: "F1",
  [KEYS.f2]: "F2",
  [KEYS.f3]: "F3",
  [KEYS.f4]: "F4",
  [KEYS.f5]: "F5",
  [KEYS.f6]: "F6",
  [KEYS.f7]: "F7",
  [KEYS.f8]: "F8",
  [KEYS.f9]: "F9",
  [KEYS.f10]: "F10",
  [KEYS.f11]: "F11",
  [KEYS.f12]: "F12",
  [KEYS.numLock]: "",
  [KEYS.scrollLock]: "",
  ";": ";",
  "=": "=",
  ",": ",",
  "`": "`",
  "[": "[",
  "\\": "\\",
  "]": "]",
  "'": "'",
  [KEYS.questionMark]: "?"
};
